-- MySQL Script generated by MySQL Workbench
-- Fri Apr 13 14:34:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mySteward
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mySteward
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mySteward` DEFAULT CHARACTER SET utf8 ;
USE `mySteward` ;

-- -----------------------------------------------------
-- Table `mySteward`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySteward`.`PRODUCTS` (
  `idPRODUCT` INT NOT NULL AUTO_INCREMENT,
  `barreCode` VARCHAR(13) NULL,
  `name` VARCHAR(45) NULL,
  `imgUrl` VARCHAR(200) NULL,
  `brand` VARCHAR(45) NULL,
  PRIMARY KEY (`idPRODUCT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mySteward`.`STOCKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySteward`.`STOCKS` (
  `idSTOCK` INT NOT NULL AUTO_INCREMENT,
  `quantity` DECIMAL(5,2) NOT NULL,
  `expiration_date` DATETIME NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idSTOCK`),
  INDEX `FKProduct_idx` (`idProduct` ASC),
  CONSTRAINT `FKProductStock`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mySteward`.`PRODUCTS` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mySteward`.`PRODUCTS`
-- -----------------------------------------------------
START TRANSACTION;
USE `mySteward`;
INSERT INTO `mySteward`.`PRODUCTS` (`idPRODUCT`, `barreCode`, `name`, `imgUrl`, `brand`) VALUES (1, '1234', 'test', NULL, 'IG2I');
INSERT INTO `mySteward`.`PRODUCTS` (`idPRODUCT`, `barreCode`, `name`, `imgUrl`, `brand`) VALUES (2, '5678', 'testDecimal', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mySteward`.`STOCKS`
-- -----------------------------------------------------
START TRANSACTION;
USE `mySteward`;
INSERT INTO `mySteward`.`STOCKS` (`idSTOCK`, `quantity`, `expiration_date`, `idProduct`) VALUES (DEFAULT, 1, NULL, 1);
INSERT INTO `mySteward`.`STOCKS` (`idSTOCK`, `quantity`, `expiration_date`, `idProduct`) VALUES (DEFAULT, 0.5 , NULL, 2);

COMMIT;

